### PR TITLE
Update CSS Regions.md

### PR DESCRIPTION
**Pull request by slightlyoff**
Refs #47

### CODE REVIEW

**Comment by twirl** [comment]
I'd prefer to keep some note that developers should be able to define regioned layout without splitting content into several DOM Elements and defining supersets.

**Comment by astearns** [comment]
On the issue of use cases, while the updated introduction has vastly simplified the examples, it does list in the prose all of the use cases that have been discussed for named flows:  "custom overflow handling, aggregating content, linked display boxes, magazine-style layout, and flowing content through areas in a paginated view"
Each of these (aside from paginated views, which is detailed in css-page-template) has at least one example in the spec.

**Comment by twirl** [comment]
@astearns There are four examples in the spec: general syntax, inserting ads, menu chaining, and content aggregation. Though rich layouts are mentioned, there is no detailed description nor example, and no description how to make semantic markup.

**Comment by astearns** [comment]
@twirl The intro has four examples, but there are more later on in sections 3, 5, and 7. The menu example shows custom overflow handling, example 4 shows content aggregation, almost all show linked display boxes, and magazine-style layout is shown in the visual formatting example in section 7.5.
I agree with your point on semantic markup. But I don't see a lack of use cases and examples.

**Comment by twirl** [comment]
@astearns Okay, let's say it this way: though there are examples in the text, the spec still lacks descriptions of intrinsic use cases and doesn't cover semantic difficulties that arise from them.

**Comment by astearns** [comment]
@twirl Hmm. Since the introduction is meant to cover use cases, it's failing in some way I'd like to fix. The examples (particularly 2 and 3) really are the distilled, simple use cases behind the feature. They show how content (this) can be assigned to boxes (there). Everything else is built out of that idea.
So should I:
1. Better describe the simple examples to demonstrate that they are the intrinsic use cases?
2. Add more complex examples?
3. Not worry about 2 or 3 until the current semantic problem is fixed?

**Comment by twirl** [comment]
@astearns There is some confusion: as *examples* cases 2 and 3 are ok, they are simple enough and they demonstrate basic CSS Regions features. But as *use cases* they are just misleading since CSS Regions primary aim, as I understand it, is allowing complicated layouts, not just chaining menus and inserting ads.

We (the TAG, I mean) aren't trying to tell you how to do your job, just raising concerns and giving advice; in my opinion, examples in use cases section should illustrate intended usage of the API, so there is no need to make them as simple as possible — just the opposite, they should be as complex as intended usage.

**Comment by astearns** [comment]
@twirl OK, thanks. The simple examples were a replacement for a problematic example that was *more* complex than the intended usage, and perhaps I swung too far in the simple direction. But as we gained experience with giving the feature to designers to use, we found that actual usage tended towards the simple end. The menu example was pulled directly from a widely-used site, and I've gotten more and better engagement with that example than any other I've used in the spec.

**Comment by travisleithead** [comment]
Merging comments made in TAG meeting in SFO. We think we have addressed the comments at that time, but if the above comments are still relevant to the current state of CSS Regions please file new issues for them. Thanks!

**Pull request merged**
