### PR TITLE
Add reviewed specs to readme (closes #102)

### LINKED ISSUE #102: Dated Space
There has been some [feedback](https://twitter.com/tobie/status/695986377767444481) from the [community](https://twitter.com/briankardell/status/696132998220140545) regarding the directory structure in this repository. The proposal is to migrate away from dated space but preserve the links in some way. /cc @bkardell @tobie @domenic @marcoscaceres

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Comment by mnot** [comment]
A++ would elect to TAG again

**Comment by marcoscaceres** [comment]
heh. r?

**Comment by tobie** [comment]
r+

**Comment by tobie** [comment]
Someone (which shall remain nameless) gave me merge power. Should I use it?

**Pull request merged**
